name: Lint

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  lint:
    name: Run Ruff Linter & Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run Ruff linter
        run: python -m ruff check .

      - name: Check formatting with Ruff
        run: python -m ruff format . --check